modLoader="javafml"
loaderVersion="[34,)"
license="GNU"
issueTrackerURL="https://github.com/ApexModder/ItemResistance/issues"

[[mods]]
modId="itemresistance"
version="${file.jarVersion}"
displayName="ItemResistance"
updateJSONURL="https://raw.githubusercontent.com/ApexModder/ItemResistance/main/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/itemresistance"
# logoFile="logo.png"
# credits=""
authors="ApexModder"
description='''
Gives dropped block items explosion resistance, as if they were placed.

TNT wont blow up dropped obisidan item stacks.
'''

# Minecraft & Forge dependencies are optional
# and not required, all mods are loaded after these
# but for completness best to include them
[[dependencies.itemresistance]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemresistance]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"

# Required dependencies
# NO-OP

# Optional dependencies
# NO-OP