modLoader="javafml"
loaderVersion="[35,)"
license="GNU"
issueTrackerURL="https://github.com/ApexModder/ItemResistance/issues"

[[mods]]
modId="itemresistance"
version="${file.jarVersion}"
displayName="ItemResistance"
updateJSONURL="https://raw.githubusercontent.com/ApexModder/ItemResistance/main/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/itemresistance"
#logoFile="logo.png"
#credits=""
authors="ApexModder"
description='''
Gives dropped block items explosion resistance, as if they were placed.

TNT wont blow up dropped obisidan item stacks.
'''

[[dependencies.itemresistance]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.itemresistance]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"
